# Generated by Django 4.1 on 2023-09-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField(auto_now=True)),
                ('priority', models.CharField(max_length=100)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmanagementapp.customuser')),
            ],
        ),
    ]
